### ISSUE TITLE
Unable to find .env-git-ssh

### ISSUE THREAD

**Issue by dmclark** [123andy/redcap-docker-compose#10]
The  docs mention .env-git-ssh,  but I cannot find it.

Thanks

**Comment by 123andy** [comment]
Hey @dmclark -

What that file contains is a remote SSH key that allows it to pull from a private git repo...
 should probably pull that out as it isn't really relevant to a local dev instance of REDCap.

How did things work otherwise?

**Comment by dmclark** [comment]
Right, in our case, that is exactly what we need. We have a gitla[b server that we want to pull this & other stuff from.

I'm using this as a starting point

**Comment by 123andy** [comment]
removed ssh stuff out of this repo for now - not for intended audience.
