### ISSUE TITLE
Issue with $SSH_DIR

### ISSUE THREAD

**Issue by dmclark** [123andy/redcap-docker-compose#12]
Hi Andy,
For some reason, in:
https://github.com/123andy/redcap-docker-compose/blob/dbe3b445a5eda0dff39614096ce0a53daa4098b5/rdc/override-web/startup-scripts/20-subrepo_init.sh#L24

$SSH_DIR is /var/www/.ssh which is not used by ssh

**Comment by 123andy** [comment]
I've removed most of the ssh stuff from this as it added unnecessary complications...
