### ISSUE TITLE
MacOS feature? 

### ISSUE THREAD

**Issue by HaukeBartsch** [123andy/redcap-docker-compose#13]
Hi Andy,

On MacOS any zip file gets is unpackaged upon download (redcapX.X.X.zip). If the user right-click 'compress' the created directory he/she ends up with a wrong packaging (zip of folder with content instead of zip with content). There is an error message at that point but its hard to relate to the problem. Would be great if the installer would be hardened against that eventuality.

best 
   Hauke

**Comment by 123andy** [comment]
Hey @HaukeBartsch - Are you saying that you are using the 'select where the zip is located' option during installation and you are having a problem where the zip file downloaded from the community site is auto-expanded on download?  

My browser does not auto-expand zip files (Chrome or Firefox) - but it appears that Safari does this by default.  I never thought about that.  You can turn this feature off here:
https://wiki.umbc.edu/pages/viewpage.action?pageId=31919091

Or, we could make the zip-scanner be smart enough to look inside of the parent folder if it didn't find the right files in the main folder.  I doubt I'll have time to catch this case, but am open to a pull request :-)

-A

**Comment by HaukeBartsch** [comment]
Sounds good. Thanks for the link to turn this behavior off. I will let you know about the merge request.
