### ISSUE TITLE
E: Package 'ssmtp' has no installation candidate (apt-get)

### ISSUE THREAD

**Issue by aldefouw** [123andy/redcap-docker-compose#15]
Hi Andy - 

It appears that apt-get package manager can no longer find `ssmtp` when you try to build the web container.

Here is the failure notice:

```
E: Package 'ssmtp' has no installation candidate
ERROR: Service 'web' failed to build: The command '/bin/sh -c apt-get update -qq &&     apt-get -yq --no-install-recommends install     libapache2-mod-shib2     ssmtp     git     ssh     wget     libpng-dev     libzip-dev     zip     && docker-php-ext-configure zip --with-libzip     && docker-php-ext-install gd zip mysqli     && rm -r /var/lib/apt/lists/*' returned a non-zero code: 100
```

Here's the trouble spot:
https://github.com/123andy/redcap-docker-compose/blob/master/rdc/docker-web/Dockerfile#L10

You already have `apt-get update` command issued, so I'm not sure what the fix will be.

Thanks,
Adam

**Comment by 123andy** [comment]
Thanks for letting me know.  I'll work on a fix today!

**Comment by 123andy** [comment]
Fixed - replaced with msmtp
