### ISSUE TITLE
Old info left in .env

### ISSUE THREAD

**Issue by ddunsmuir** [123andy/redcap-docker-compose#19]
There's a line in your comments that refer to "REDCAP_DOWNLOAD_DIR below", which isn't in the file. It was removed many commits ago. Not sure what you want to change that to:
https://github.com/123andy/redcap-docker-compose/blob/82bd9d4e62e0205079996917f1a796dd05ccd464/rdc/.env#L53

Additionally, there's a sentence that just consists of "NOTE T" before the MYSQL_PORT. What should we note?
https://github.com/123andy/redcap-docker-compose/blob/82bd9d4e62e0205079996917f1a796dd05ccd464/rdc/.env#L64

**Comment by 123andy** [comment]
cleaned up and refactored.
