### ISSUE TITLE
Tweaking for production

### ISSUE THREAD

**Issue by devincowan** [123andy/redcap-docker-compose#20]
Your Wiki mentions that this docker compose should not be used for production, but that Stanford uses something similar.

I'm curious what changes are recommended to make this more suitable for production? Of course, some port forwarding, cert files...what else?

Thanks!

**Comment by 123andy** [comment]
I think that was my cautious disclaimer to say I'm not responsible...   In truth, there probably aren't many issues other than setting your php.ini settings in the apache-override folder to be appropriate for a production server (and obviously setting a more secure password for the database!).  You might also want to restrict root access to the database to different IPs.  

I don't see any real problems with using this for production or as inspiration for production...  

I've thought of removing the whole overrides thing.  The idea there was to make it so you could use it for more than just REDCap and customize it for any LAMP platform, but it seems to hold up.

We've been running our production on docker-compose for over a year now and had only one instance where the engine got hung up and required a restart... Hard to say what caused that.

Good luck and please submit any feedback/improvements you might have.
