### ISSUE TITLE
Best strategy for multiple instances?

### ISSUE THREAD

**Issue by pbchase** [123andy/redcap-docker-compose#26]
@123andy, as I was working on PR #25 I got to wondering what your intent was for managing instances and why you have the `www` and `logs` folders outside the `rdc` folder. Their current location incentivizes me to copy the entire repo folder to make a new instance. If `logs` and `www` were children of `rdc` then I could just copy the rdc folder to a new name. I'm not sure which is better.  

I ask because I've written some updates to _Can I run more than one instance of REDCap-Docker-Compose at the same time?_. I thought I'd get your input before I went any further.

**Comment by 123andy** [comment]
Hmm - variables are:
- php versions (same web folder) 
- database versions (same web folder)
- various redcap versions (different web folders or same folder with different webroots).

I think my thoughts were not to confuse most users with all the docker stuff so having it compartmentalized seemed good.   I don't really have a strong opinion on it.  We could offer more .env templates that have it in different locations too...

**Comment by pbchase** [comment]
I think I'll document what you have rather than change it at this time. I still need to explore the configurability of what you have created. I am quite certain I do not yet grasp it all.

**Comment by pbchase** [comment]
I added the planned documentation in PR #27

**Comment by pbchase** [comment]
fixed by PR #27
