### ISSUE TITLE
Shell scripts for multi-instance management

### ISSUE THREAD

**Issue by pbchase** [123andy/redcap-docker-compose#32]
@123andy, 

@ChemiKyle and I are really enjoying to this docker environment for our development work. We continue to look for ways to get our work done faster. Today I wrote two shell scripts to make that work easier. They are both a bit crude, but they are effective. 

[make_rdc_instance.sh.txt](https://github.com/123andy/redcap-docker-compose/files/4149899/make_rdc_instance.sh.txt) is a script designed to copy the rdc folder, make the host ports unique and localize the www and logs folder to the copy of rdc. It implements my advisories in https://github.com/123andy/redcap-docker-compose/tree/master/rdc/documentation#can-i-run-more-than-one-instance-of-redcap-docker-compose-at-the-same-time and goes a little further.

[synch_module.sh.txt](https://github.com/123andy/redcap-docker-compose/files/4149917/synch_module.sh.txt) lives in a hypothetical ./modules folder at the root of the repo. It is designed synchronize changes to a list of modules out to a list of redcap instances, presumably created by `make_rdc_instance.sh`. These tools work together to make simultaneous module testing in multiple REDCaps a reality.

Are you interested in these scripts? If so, is BASH a problem? Will BASH marginalize our Windows users or is the audience already comfortable at a shell?

I'd love to get your feedback. If you like this Kyle or I can add some polish and package either or both of these in a PR.

**Comment by 123andy** [comment]
Hi guys,

I'm interested in the functionality but haven't had time to review.  To get around the bash we could execute them in a docker container too...

-A

________________________________

**Comment by pbchase** [comment]
@123andy, these scripts needs to run in the host context. One is making copies of the `rdc` folder. The other is rsyncing a developer's edits on module code to the various www/modules folders in those copies of the rdc folders. Neither could effectively be run inside an rdc container.

**Comment by 123andy** [comment]
I haven't looked at it that closely but there is always a hack to be found - even if mounting the /rdc folder as a volume in a one-liner :-)

**Comment by pbchase** [comment]
I didn't explain myself well. These scripts have to run from the host. One reads from the host file system. The other writes to the host file system and then does a `docker-compose up` to start the environment it just configured.  I made a gist for the latest version copy of the latter tool, [make-rdc-instance.sh](https://gist.github.com/pbchase/616dc9f9bf38a03e6c7d46f639ebe053)

I think I might have the solution to the BASH issue for Windows users. If we direct the Windows uses to GUI tools like Github Desktop, we can have them use the git-bash terminal that ships with it. 

This flows out of a GUI-based approach I took when giving a REDCap module development class last week at UAMS. I found myself in front of a large audience of non-developers with windows laptops. To serve them, I wrote a [guide](https://github.com/pbchase/redcap_external_module_development_guide/blob/uams-class-notes/docs/development_class.md) that will become part of a larger [module development guide](https://github.com/ctsit/redcap_external_module_development_guide) we have been working on. All of this dev work centers around your redcap-docker-compose, because we think it is the tool for creating a local REDCap. We want to make rdc better for us and for the broader community of REDCap developers and admins.

**Comment by 123andy** [comment]
ahh. - sounds good.

**Comment by 123andy** [comment]
Just closing this for now - if there is more work to be done, a new issue can be created.

**Comment by pbchase** [comment]
OK, for those who might stumble upon this, I offer a revised URL for the gist for [make_rdc_instance.sh](https://gist.github.com/pbchase/5bc2de5bd40e330fb4889d32065269a2)
