### ISSUE TITLE
Better performance on MACs?

### ISSUE THREAD

**Issue by 123andy** [123andy/redcap-docker-compose#34]
I was having some pretty poor performance on MAC for my docker-compose and stumbled across this: 

https://engageinteractive.co.uk/blog/making-docker-faster-on-mac

Adding the `:delegated` suffix to the mapped volumes made a pretty be improvement. 

![image](https://user-images.githubusercontent.com/7461553/78301530-0d283a00-74ee-11ea-88e7-ae7bf7a1a8af.png)

 I'm just playing with it to see if I find tailing logs to be delayed, etc.. but so far so good.   Thought I would share in case any of you develop on macs and have performance issues with the filesystem mapping...I'm thinking of putting it into the rdc repo.Actually, I was thinking of doing what you recommended which was to build shell scripts for stop, start, and common actions that people do.  In those, we could have a mac start script that applies a second docker-compose.mac.yml file on top of the base one that overrides the volumes with this fag.Similarly, you could have an override like docker-compose.phpmyadmin.yml that adds the phpmyadmin to the compose then in the batch file it would be something like:

```
docker-compose -f docker-compose.yml -f docker-compose.mac.yml -f docker-compose.phpmyadmin.yml
```

Might be a lot easier for people to understand and use....  

Thoughts, @pbchase @ChemiKyle ?

**Comment by pbchase** [comment]
@123andy, @ChemiKyle and I do develop on macs. I haven't seen performance issues, but Kyle might feel differently. 

I'm intrigued by your example of layered docker-compose.yml files. I didn't know you could do that. That could be useful. :-)

As to shell scripts, if you are considering going down that slippery slope with us, this gist is one of my favorite RDC-related creations. It's pretty stable too.  See [Create and start a new REDCap instance using redcap-docker-compose](https://gist.github.com/pbchase/616dc9f9bf38a03e6c7d46f639ebe053)

**Comment by ChemiKyle** [comment]
@123andy, I am on a much older mac than @pbchase and I do see intense resource usage to the point that my system slows to a crawl. I am testing this out and will report back.  
Are you setting all volumes to delegated or excluding the database ones? At the moment I've only applied this to the volumes that are part of the `web` service.

I like the idea of splitting out system-specific `.yml` files and build scripts as I also occasionally spin REDCap up on my Debian machine - we're pretty busy with COVID work at the moment so I can't offer any more insight on that unfortunately.

**Comment by 123andy** [comment]
I put this on all the 'mapped' volumes, but I think the critical ones are those that are mapped externally to the mac's file system.

-A

________________________________

**Comment by 123andy** [comment]
Another option is to try disabling xdebug to see if that helps?

**Comment by ChemiKyle** [comment]
A recent Docker update (around the end of July) gave a huge boost in performance for us, I recall the changelog mentioning a memory leak in MacOS being fixed.

Here are my relevant Docker version numbers:
- Docker Desktop: 2.3.0.5 (stable)
- Engine: 19.03.12
- Compose 1.27.2

I still have all volumes set to `delegated` (except for the additional modules volume I've added), I haven't had any performance issues unless I'm running multiple instances concurrently.
