### ISSUE TITLE
Docker-cron regularly crashes due to trying to create a user that already exists

### ISSUE THREAD

**Issue by ChemiKyle** [123andy/redcap-docker-compose#35]
I believe the root of the problem is that Alpine Linux follows different rules than one might expect. See the following lines:

https://github.com/123andy/redcap-docker-compose/blob/6ca26568f9f6b87aa969e30b10b5560d038a51f0/rdc/docker-cron/entrypoint.sh#L6-L13

```sh
adduser -D -H -u 501 www-data
```

Is creating a user _named_ www-data with _uid_ 501; 501 is being considered an arg to the flag -u and _not_ the username. There is no `www-data` group.

Additionally, the meaning of the `-u` flag is not consistent between `adduser` and `id`. For `id` the `-u` flag corresponds to the `username`.

```bash
if [ $(id -u $APACHE_RUN_USER_ID >/dev/null 2>&1) ]
```

Evaluates to false because `id -u 501` should actually be `id -u www-data`. For id, `-u` flag means user**name** not user**id**.

**Comment by 123andy** [comment]
Great catch.  Do you have a fix?  The idea here was to allow the cron user to write to the mapped logging table - which means it should have the same UID as the mac user...

**Comment by ChemiKyle** [comment]
I don't consider it a proper fix, but changing line 7 as below should get a running system working. 
```sh
     if [ $(id -u www-data >/dev/null 2>&1) ]; then 
```

@pbchase actually found the failure to add user issue about a month ago, I just discovered it's because of the `-u` disparity; @pbchase stopped the issue by simply commenting out line 11.

As for an actual fix, I unfortunately have little time to improve tools at the moment; I did try changing  
```sh
adduser -D -H -u "$APACHE_RUN_USER_ID" www-data
```
to  
```sh
adduser -D -H -u "$APACHE_RUN_USER_ID" -G www-data "$APACHE_RUN_USER_ID"
```
But that did not work after spinning down and back up again - attaching a terminal to the `redcap_cron` container and running `id -u 501` still gave an `unknown user 501`, and the `tail` of `/etc/passwd` was: `www-data:x:501:501:Linux User,,,:/home/www-data:`, so as far as having a user with the same UID your goal is accomplished.  
Sorry I can't offer a PR, we're pretty swamped over here.

**Comment by pbchase** [comment]
@123andy, we were having trouble figuring out your intent in having this code. I can't see how it would matter to the cron process, but maybe I'm missing something. 

As @ChemiKyle  said, we are swamped. We've been ignoring this 'cause it didn't matter until today when we are trying to get module crons to work right. At least we have some hacky fixes that will will suffice until we can treat the problem instead of the symptom.

**Comment by 123andy** [comment]
Hi @pbchase  - the intent is to ensure that when the cron container writes to the log directories (and runs log-rotate) - it would have appropriate permissions for the cross-mounted folder.  These permissions are really driven by the user ID (not the name).  So, you want to have your docker cron on mac running under the same id as your mac user.  I didn't do much testing here, obviously.

**Comment by pbchase** [comment]
@123andy, thanks for that details, I forgot about the log volume. I'll see what I can do.
