### ISSUE TITLE
Error running 'docker-compose up'

### ISSUE THREAD

**Issue by HaukeBartsch** [123andy/redcap-docker-compose#4]
Hi Andy,

Trying to run docker-compose up in the repository root. 

WARNING: The WEB_PORT variable is not set. Defaulting to a blank string.
WARNING: The WEB_OVERRIDES variable is not set. Defaulting to a blank string.
WARNING: The WEBROOT_DIR variable is not set. Defaulting to a blank string.
WARNING: The LOGS_DIR variable is not set. Defaulting to a blank string.
WARNING: The MYSQL_DIR variable is not set. Defaulting to a blank string.
WARNING: The MYSQL_OVERRIDES variable is not set. Defaulting to a blank string.
WARNING: The MYSQL_PORT variable is not set. Defaulting to a blank string.
WARNING: The CRONTAB_FILE variable is not set. Defaulting to a blank string.
WARNING: The CRON_LOGROTATE_DIR variable is not set. Defaulting to a blank string.
WARNING: The MAILHOG_OUTGOING_SMTP_FILE variable is not set. Defaulting to a blank string.
WARNING: The REDCAP_DOWNLOAD_DIR variable is not set. Defaulting to a blank string.
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.db.ports is invalid: Port ranges don't match in length
services.web.ports is invalid: Port ranges don't match in length

I guess this issue is caused by a missing .env files in the repository. Am I doing something wrong?

**Comment by 123andy** [comment]
Sorry, Hauke,

I had a `.gitignore` entry that kept out the .env file.  I just pushed the update.  Please pull the current repo and try again.  Sorry for the confusion!

-A

**Comment by HaukeBartsch** [comment]
works like a charm
