### ISSUE TITLE
for Mac with Apple silicon - need to change MySQL version

### ISSUE THREAD

**Issue by keiko-ota** [123andy/redcap-docker-compose#52]
Thank you for sharing these contents and information. It's very useful and helpful.

Here is the reference information when using the Mac with Apple silicon(M1). I could create the container, but needed to change MySQL info as follows.

file:
rdc\docker-mysql\Dockerfile

```
#FROM mysql:5.7
FROM mysql/mysql-server:5.7.28
```

**My client environment:**
Mac mini (M1, 2020) / Chip Apple M1 / macOS Big Sur version 11.4
Docker version 20.10.6, build 370c289

**Comment by 123andy** [comment]
We now have a comment in the mysql dockerfile about ARM compatibility.  Thx.
