### ISSUE TITLE
Local testing environment binds to the public port

### ISSUE THREAD

**Issue by pbchase** [123andy/redcap-docker-compose#53]
The local testing environment defined in [docker-compose.yml](https://github.com/123andy/redcap-docker-compose/blob/master/rdc/docker-compose.yml) binds to the public port. This allows access to the HTTP and other interfaces from any host that can get a route to the device where the container is running. Combined with weak credentials often used in development environments could create a risk of attack.

To mitigate this, we could bind the interfaces only to localhost, aka 127.0.0.1.  e.g. at https://github.com/123andy/redcap-docker-compose/blob/7c64f2d9e71a3b80225895908ceed532dbbb2ad9/rdc/docker-compose.yml#L18

We could instead write 

```
- "127.0.0.1:${WEB_PORT}:80"
```

Would you be interested?  I could write the PR.

**Comment by 123andy** [comment]
Sure - I can see cases where this might be desirable.  At a minimum, we should include documentation in the .env file for the WEB_PORT variable that explains this.  There are certainly times when you want to permit others to connect but perhaps that shouldn't be the default...

**Comment by 123andy** [comment]
I suppose the same should apply if you are publicly exposing the mysql instance...

**Comment by pbchase** [comment]
@123andy I submitted PR #56 that hides all of those exposed ports from points outside of the host

**Comment by 123andy** [comment]
This has been incorporated to the latest merge.  Thanks!
