### ISSUE TITLE
Getting 20-subrepo_init.sh to work

### ISSUE THREAD

**Issue by dmclark** [123andy/redcap-docker-compose#58]
@123andy I've been a huge fan of this and all your other work since joining the redcap community

This is mostly from my limited docker knowledge, but I'm having trouble understanding  $HOME_DIR  in the web container -- there does not seem to be one.

Any thoughts?

Thanks

**Comment by dmclark** [comment]
I notice that APACHE_RUN_USER_ID is set in .env but not APACHE_RUN_USER

**Comment by 123andy** [comment]
Hey David,

The subrepo init was from a previous project so isn't too relevant unless you really want to use it.  We aren't currently using it in our dev instances so I haven't done much troubleshooting...

This package is due for an overhaul given changes for php 8, xdebug 3, and more but I haven't gotten around to it...

**Comment by 123andy** [comment]
I've decided to remove subrepo_init from the package as it is not commonly used.
