### ISSUE TITLE
issue while installing the redcap instance 

### ISSUE THREAD

**Issue by dmarcicLIH** [123andy/redcap-docker-compose#66]
Hi, 
I have got this particular issue but i don't see what i am doing wrong : 
![image](https://user-images.githubusercontent.com/53478415/181209459-5eab653a-aa03-4e39-8521-8fe83a2191dd.png)

Can you help me please ? 
Thanks 
David

**Comment by dmarcicLIH** [comment]
fixed: i have got a in-between redcap folder into the zip

**Comment by 123andy** [comment]
Great!
