### ISSUE TITLE
Message: CRITICAL ERROR: REDCap server is offline!

### ISSUE THREAD

**Issue by tranpl** [123andy/redcap-docker-compose#77]
I'm having issues with getting the installation wizard up after initial run. Initially, I got to the installation wizard screen; stopped in the middle of installation to adjust .env setting. I changed the phpmyadmin port, then did docker-compose up. I'm unable to get back to that installation screen and get the "CRITICAL ERROR: REDCap server is offline!" message. 
I then removed all the images/containers/volumes. I did a force create build etc. Its still doing the same thing.

I looked at phpmyadmin and the 'redcap' database is clean, however phpmyadmin shows initial message:

`Error in processing request
Error code: 200
Error text: OK (rejected)
It seems that the connection to server has been lost. Please check your network connectivity and server status.`

I've torn the containers/images/volumes up many times after a reboot. I uninstalled docker and reinstalled. Its still showing the same message, any ideas?

**Comment by 123andy** [comment]
Not sure...  Probably best to try a quick zoom call...

**Comment by tranpl** [comment]
Thanks Andy! All resolved. We removed the unfinished redcap installation files (it did not finish downloading) in the www  folder and restarted the installation wizard =)
