### ISSUE TITLE
Cron job not running

### ISSUE THREAD

**Issue by johannestoger** [123andy/redcap-docker-compose#80]
Hi, after installing with RedCap v13.7.1 I get warnings/errors in the Control Center that the cron job is not running. Looking at the terminal output I have the following error about once per minute:

> redcap_2022_1_cron        | /bin/ash: redir error

Any ideas about what is wrong here?

**Comment by hpotier** [comment]
same for me!

**Comment by 123andy** [comment]
Hmm.  Can you try again with the latest version?  It is working fine for me.   Are you on a PC or a MAC?   Happy to meet up and go over it if it still isn't working.  -A

**Comment by 123andy** [comment]
I'm going to close this one out for now.  Please re-open if this is still an issue and we can perhaps work on it.
